--- 
env: 
  - DOCKER_COMPOSE_VERSION=3
language: php
php: 
  - "7.1"
script: 
  - "USER_ID=root docker-compose up -d"
  - "docker-compose exec web composer install -n"
  - "docker-compose exec web bin/console d:d:d --if-exists --force --env=test"
  - "docker-compose exec web bin/console d:d:c --env=test"
  - "docker-compose exec web bin/console d:schema:update --force --env=test"
  - "docker-compose exec web mkdir -p build/logs"
  - "docker-compose exec web vendor/bin/phpunit -c phpunit.xml.dist"
after_success:
  - "docker-compose exec web php php-coveralls.phar"
services: 
  - docker