--- 
language: php
php: 
  - "7.1"
cache:
    directories:
        - $HOME/.composer/cache
warnings_are_errors: false

install: 
  - "composer install -n"
  - "cp app/config/parameters.yml.travis app/config/parameters.yml"
  - "cp app/config/config_test.yml.travis app/config/config_test.yml"
  - "bin/console d:d:d --if-exists --force --env=test"
  - "bin/console d:d:c --env=test"
  - "bin/console d:schema:update --force --env=test"
scritpt:
  - "mkdir -p build/logs"
  - "vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml"

after_success:
  - "php php-coveralls.phar"
services: 
  - mysql 