version: '3'
services: 
    db: 
        container_name: todolist_db
        image: mysql:5.7
        restart: always
        ports: 
            - 3306:3306
        volumes: 
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: "todolist, todolist_test"
            MYSQL_USER: todolist
            MYSQL_PASSWORD: todolist
        networks: 
            - todolist

    phpmyadmin:
        container_name: todolist_phpmyadmin
        image: phpmyadmin
        restart: always
        depends_on:
            - db
        ports:
            - 8090:80
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: root
        networks: 
            - todolist
    
    maildev:
        container_name: todolist_maildev
        image: maildev/maildev
        restart: always
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        ports:
            - 8081:80
        networks: 
            - todolist
    
    web:
        container_name: todolist_web
        build: .
        restart: always
        depends_on:
            - db
        user: ${USER_ID}
        ports:
            - 8000:80
        environment: 
            APP_ENV: dev
            DATABASE_URL: mysql://todolist:todolist@db:3306/todolist?serverVersion=5.7
            MAILER_DSN: smtp://maildev:25
            SYMFONY__DB_HOST: db
            SYMFONY__DB_PWD: root

        volumes: 
            - .:/var/www/html
            - ./.docker/host:/etc/apache2/sites-enabled
            - ./.docker/php.ini:/usr/local/etc/php/php.ini
        networks: 
            - todolist

    # blackfire:
    #     container_name: todolist_blackfire
    #     image: blackfire/blackfire:2
    #     ports: ["8307"]
    #     environment:
    #         # Exposes BLACKFIRE_* environment variables from the host
    #         BLACKFIRE_SERVER_ID: $BLACKFIRE_SERVER_ID
    #         BLACKFIRE_SERVER_TOKEN: $BLACKFIRE_SERVER_TOKEN
    #         BLACKFIRE_CLIENT_ID: $BLACKFIRE_CLIENT_ID
    #         BLACKFIRE_CLIENT_TOKEN: $BLACKFIRE_CLIENT_TOKEN
    #     networks: 
    #         - todolist

volumes: 
    db-data:

networks: 
    todolist:
