language: php
php:
  - '7.0'
  - '7.1'

script:
   - composer install
   - composer init-db
   - vendor/bin/phpunit

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=3.9

# safelist
only:
  - audit